### ISSUE TITLE
Create toolbox panel

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-editor#7]
So that you toggle tools using 2d UI rather than spacebar.

**Comment by dmarcos** [comment]
We should get rid of modes as much as we can. We should be really forward thinking in this editor and try to understand whey other tools are the way they are instead of copying them because they’re popular/succesful. Modes is usually a pretty bad idea and the last resource. Getting rid of modes has been a personal crusade for several prominent people in the UI space for decades like Larry Tesler or Jef Raskin: https://itsthedatastupid.wordpress.com/2010/05/29/no-modes/

**Comment by caseyyee** [comment]
Oh for sure, absolutely agree with the no-modes philosophy.   Will definetly reduce the presence of mode any chance we get.

**Comment by caseyyee** [comment]
https://github.com/aframevr/aframe-editor/commit/691f78d9c47480114f3d7b026dff115c5edb123c
